/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam1;

/**
 * Contains the main buttons to running the the game page
 * @author stephenthoen
 */
public class Game extends javax.swing.JFrame {
    LoginPage log = new LoginPage();
    private int total = 0;
    Bet newbet = new Bet(); 
    
    /**    
     * Creates new form Game
     */
    public Game() {
        initComponents();
        Name.setText(GameInfo.User_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TotalMoney = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BetValue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Dice_N_1 = new javax.swing.JLabel();
        Dice_N_2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        under7 = new javax.swing.JRadioButton();
        equal7 = new javax.swing.JRadioButton();
        greater7 = new javax.swing.JRadioButton();
        outcomeL = new javax.swing.JLabel();
        Signout = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Over and Under");

        jLabel2.setText("Total In The Bank:");

        TotalMoney.setText("500");

        jLabel4.setText("What would you like to bet?");

        jLabel5.setText("$");

        jLabel6.setText("Dice #1");

        jLabel7.setText("Dice #2");

        Dice_N_1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        Dice_N_2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Dice Total:");

        DTotal.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        jButton1.setText("Click me to Roll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        under7.setText("Under 7");
        under7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                under7ActionPerformed(evt);
            }
        });

        equal7.setText("7");
        equal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal7ActionPerformed(evt);
            }
        });

        greater7.setText("Greater than 7");
        greater7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greater7ActionPerformed(evt);
            }
        });

        outcomeL.setFont(new java.awt.Font("Lucida Grande", 3, 48)); // NOI18N

        Signout.setText("Sign Out");
        Signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoutActionPerformed(evt);
            }
        });

        Name.setText("jLabel3");

        jLabel3.setText("Player:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(TotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BetValue, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Dice_N_1)
                                        .addComponent(jLabel6))
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(DTotal)
                                        .addComponent(Dice_N_2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(under7)
                                .addGap(35, 35, 35)
                                .addComponent(equal7)
                                .addGap(46, 46, 46)
                                .addComponent(greater7))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(outcomeL)
                .addGap(243, 243, 243))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Name))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Signout)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Signout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TotalMoney))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BetValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(under7)
                    .addComponent(equal7)
                    .addComponent(greater7))
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dice_N_1)
                    .addComponent(Dice_N_2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(DTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(outcomeL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
  * most things occur off this button click. 
  * @param evt 
  */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Random_Dice rand = new Random_Dice();
        int dice_1 = 0;
        int dice_2 = 0;
        int dicetotal = 0;
        int userbet = 0;
        
        try {
            userbet = Integer.parseInt(BetValue.getText());
            
            int bet_type = 0;
            
            if (under7.isSelected()) {
                bet_type = 6;
                
            } else if (equal7.isSelected()) {
                bet_type = 7;
                
            } else if (greater7.isSelected()) {
                bet_type = 8;
            } else {
                bet_type = 0;
            }
            
            if (total == 0) {
                total = GameInfo.start();
            } else {
                total = newbet.gettotal();
            }
            
            dice_1 = rand.dice_1();
            
            dice_2 = rand.dice_2();
            
            dicetotal = rand.print_dice_total();
            
            
            newbet.bet(userbet, bet_type,
                    total, dicetotal);
            
            int finaltotal = newbet.gettotal();
            String outputtotal = String.valueOf(finaltotal);
            
            String diceSingle_1 = String.valueOf(dice_1);
            String diceSingle_2 = String.valueOf(dice_2);            
            String total_dice = String.valueOf(dicetotal);
            Dice_N_1.setText(diceSingle_1);
            Dice_N_2.setText(diceSingle_2);
            DTotal.setText(total_dice);
            TotalMoney.setText(outputtotal);
            outcomeL.setText(newbet.getoutcome());
            
            //clean up for next round
            BetValue.setText("");
            under7.setSelected(false);
            equal7.setSelected(false);
            greater7.setSelected(false);
        } catch (Exception ex) {
            ex.getMessage();
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void under7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_under7ActionPerformed
        // TODO add your handling code here:
        equal7.setSelected(false);
        greater7.setSelected(false);
    }//GEN-LAST:event_under7ActionPerformed

    private void equal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal7ActionPerformed
        // TODO add your handling code here:
        under7.setSelected(false);
        greater7.setSelected(false);
    }//GEN-LAST:event_equal7ActionPerformed

    private void greater7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greater7ActionPerformed
        // TODO add your handling code here:
        under7.setSelected(false);
        equal7.setSelected(false);
    }//GEN-LAST:event_greater7ActionPerformed

    private void SignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoutActionPerformed
        // TODO add your handling code here:
        log.setVisible(true);
        Game.this.setVisible(false);
    }//GEN-LAST:event_SignoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BetValue;
    private javax.swing.JLabel DTotal;
    private javax.swing.JLabel Dice_N_1;
    private javax.swing.JLabel Dice_N_2;
    private javax.swing.JLabel Name;
    private javax.swing.JButton Signout;
    private javax.swing.JLabel TotalMoney;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton equal7;
    private javax.swing.JRadioButton greater7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel outcomeL;
    private javax.swing.JRadioButton under7;
    // End of variables declaration//GEN-END:variables
}
